title: Oricad
email: marynissen.simon@gmail.com
description: |- # this means to ignore newlines until "baseurl:"
  Oricad is a CAD (computer-assisted design) program for origami.
  Design, diagram and fold origami models.
baseurl: 'https://oricad.org'
url: 'https://oricad.org'
github_username:  oricad

# Build settings
theme: minima
plugins:
  - jekyll-feed

# https://github.com/pmarsceill/just-the-docs
# https://pmateusz.github.io/linux/2017/06/30/linux-secure-apt-repository.html
