title: Oricad
email: dev@oricad.com
description: >-
  Oricad is an open-source origami designer made to bring computer-assisted modeling to origami.
baseurl: ""
url: "https://oricad.org"
github_username: oricad

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - downloads.md
  - about.md
